### ISSUE TITLE
 Cannot install django-admin-generator because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by selbieh** [WoLpH/django-admin-generator#11]
ERROR: Command errored out with exit status 1:
   command: /home/sayed/Desktop/elham/env3/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y66_fu7_/anyjson_4b6a6ca36439448696c59be8b2ddd8a2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y66_fu7_/anyjson_4b6a6ca36439448696c59be8b2ddd8a2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cq46gy2d
       cwd: /tmp/pip-install-y66_fu7_/anyjson_4b6a6ca36439448696c59be8b2ddd8a2/
       
       
       
    

`The conflict is caused by:
    django-utils2 2.12.0 depends on anyjson>=0.3.0
    django-utils2 2.11.3 depends on anyjson>=0.3.0
    django-utils2 2.11.2 depends on anyjson>=0.3.0
    django-utils2 2.11.1 depends on anyjson>=0.3.0
    django-utils2 2.11.0 depends on anyjson>=0.3.0
    django-utils2 2.9.0 depends on anyjson>=0.3.0
    django-utils2 2.8.0 depends on anyjson>=0.3.0
    django-utils2 2.7.0 depends on anyjson>=0.3.0
    django-utils2 2.6.0 depends on anyjson>=0.3.0
    django-utils2 2.5.4 depends on anyjson>=0.3.0
    django-utils2 2.5.3 depends on anyjson>=0.3.0
    django-utils2 2.5.2 depends on anyjson>=0.3.0
    django-utils2 2.5.1 depends on anyjson>=0.3.0
    django-utils2 2.5.0 depends on anyjson>=0.3.0six
    django-utils2 2.4.0 depends on anyjson>=0.3.0six
    django-utils2 2.3.0 depends on anyjson>=0.3.0six
    django-utils2 2.2.1 depends on anyjson>=0.3.0six
    django-utils2 2.2.0 depends on anyjson>=0.3.0six
    django-utils2 2.1.0 depends on anyjson>=0.3.0six
    django-utils2 2.0.1 depends on anyjson>=0.3.0six
    django-utils2 2.0.0 depends on anyjson>=0.3.0six
    django-utils2 1.8.1 depends on anyjson>=0.3.0
    django-utils2 1.8.0 depends on anyjson>=0.3.0
    django-utils2 1.7.1 depends on anyjson>=0.3.0
    django-utils2 1.7.0 depends on anyjson>=0.3.0
    django-utils2 1.6.1 depends on anyjson>=0.3.0
    django-utils2 1.6.0 depends on anyjson>=0.3.0
    django-utils2 1.5.1 depends on anyjson>=0.3.0
`

**Comment by WoLpH** [comment]
It seems the `django-utils2` package still had a `anyjson` dependency. I've removed it now so you should be able to install using:

```
pip install -U django-admin-generator
```
