### ISSUE TITLE
Handling models in sub folders

### ISSUE THREAD

**Issue by buswedg** [wolph/django-admin-generator#13]
Great package, has helped me greatly. 

Have you considered how to handle models within subfolders of an app? I'm needing to go through and manually correct imports within admin.py, for any apps which I have models organized by subfolders. 

Note that these models are discoverable through app.get_models().

**Comment by buswedg** [comment]
Just taking a closer look at your code. Perhaps the easiest way to accomplish this would be to import all relevant models in either the root models.py, or even apps.py. And to change your PRINT_IMPORTS string accordingly.

**Comment by wolph** [comment]
It's never come up before because Django historically has had terrible support for models anywhere besides `app/models.py`. Believe me... I've tried many times in the past to organize large apps better ;)

Regardless though, if it works it shouldn't be all that hard to support it. I'll take a look :)

**Comment by wolph** [comment]
I've added a fix for it on development, can you test if this works for you?

**Comment by buswedg** [comment]
hmm odd. Doesn't seem to be generating any output to my provided admin.py path now. And I'm only seeing the below printed to terminal when running the management command.

```
from django.contrib import admin

from . import models


def _register(model, admin_class):
    admin.site.register(model, admin_class)
```

I took a quick look at your changes, and it seems that the below isn't yielding/iterating anything for me:

```
for admin_model in sorted(self, key=lambda x: x.model.__module__)
```

I'll do some digging.

**Comment by buswedg** [comment]
apologies -- the problem was on my side. So, looks like this is working.

It is however, including an unnecessary import now. I guess that'ss because you kept 'from . import models' within the PRINT_IMPORTS string.

**Comment by wolph** [comment]
Oops, it seems I reverted that change while editing :)
It's gone now. I'll create a new release as well
