### ISSUE TITLE
List filter options being repeated when using mixins

### ISSUE THREAD

**Issue by buswedg** [wolph/django-admin-generator#14]
I'm not sure if this is intended behavior, but I noticed this morning that the generated admin.py is repeating list_filter options. And seems to be related to whether those fields are related fields, or included via a model mixin. 

An example output for model 'ProfileLocation' below:

```
class ProfileLocationAdmin(admin.ModelAdmin):

    list_display = ('id', 'created_at', 'modified_at', 'profile', 'location')
    list_filter = (
        'created_at',
        'modified_at',
        'profile',
        'location',
        'id',
        'created_at',
        'modified_at',
        'profile',
        'location',
    )
    date_hierarchy = 'created_at'
```

created_at and modified_at are both datetimefields which are included via a modelmixin. While profile is a onetoone and location is a fk field.

**Comment by wolph** [comment]
That's definitely a bug... I've noticed it before but forgot to fix it. Thanks for reminding me!

**Comment by wolph** [comment]
I've created a new release that fixes this issue :)
